In [1]:
import numpy as np
import sys
from pylab import *
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

In [2]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [3]:
columns = ['Sample code number','Clump Thickness','Uniformity of Cell Size ','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei',' Bland Chromatin','Normal Nucleoli',' Mitoses ','Class'];
cancer = pd.read_csv('/content/gdrive/My Drive/4th year/Data Analytics/datafile.csv',names=columns)

In [4]:
print(cancer.head())

   Sample code number  Clump Thickness  ...   Mitoses   Class
0             1000025                5  ...          1      2
1             1002945                5  ...          1      2
2             1015425                3  ...          1      2
3             1016277                6  ...          1      2
4             1017023                4  ...          1      2

[5 rows x 11 columns]


In [5]:
cancer.drop(columns='Sample code number', inplace = True)
cancer["Class"].replace({2: -1, 4: +1}, inplace=True)

In [6]:
x = cancer.iloc[:, :-1].values
y = cancer.iloc[:, 9].values
print(cancer.head())

   Clump Thickness  Uniformity of Cell Size   ...   Mitoses   Class
0                5                         1  ...          1     -1
1                5                         4  ...          1     -1
2                3                         1  ...          1     -1
3                6                         8  ...          1     -1
4                4                         1  ...          1     -1

[5 rows x 10 columns]


In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=100) 

In [10]:
t = int(input("Number of iterations: "))

Number of iterations: 2


In [11]:
    C = 1
    n = len(x_train[0,:])
    w = np.zeros((n,1))
    y_train = [int(i) for i in y_train]
    
    for i in range(t):
        for j in range(x_train.shape[0]):
            xt = x_train[i].reshape((n, 1))
            y_dash = np.dot(w.T,xt)
            print("y" , y_dash)
            yy_dash  = y_train[i] * y_dash
            loss = max([0,1-yy_dash])
            x_square = np.power(np.linalg.norm(xt, ord=2), 2)
            tor = loss/(x_square+1/(2*C))
            
            xt = [float(i) for i in xt]
            s = tor*y_train[i] 
            temp = [x*s for x in xt]
            w = w+temp
            print("w",w)            

y [[0.]]
w [[[-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]]

 [[-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]]

 [[-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]]

 [[-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]]

 [[-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]]

 [[-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]
  [-0.06451613]]

 [[-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
  [-0.12903226]
 

ValueError: ignored

In [ ]:
def accuracy(correct,predicted):
    count=0
    n=len(correct)
    for i in range(n):
        if correct[i]==predicted[i]:
            count=count+1
    accuracy=(count/n)*100
    return accuracy

In [ ]:
resultlabeld = [] #predicted label for unseen data
vresultlabeld2 = []  #predicted label for previously seen data

#predicted values for the testing data
for x in x_test:
    x = [int(t) for t in x]
    resultlabeld.append(np.sign(np.dot(w.T,x)))
    resultlabeld = [int(i) for i in resultlabeld]
    y_test = [int(i) for i in y_test]
    print("testing accuracy: ",accuracy(y_test,resultlabeld))
    print('\n')
 
    ##predicted values for training data
for x in x_train:
    x = [int(t) for t in x]
    resultlabeld2.append(np.sign(np.dot(w.T,x)))
    resultlabeld2 = [int(i) for i in resultlabeld2]
    y_train = [int(i) for i in y_train]
    print("training accuracy: ",accuracy(y_train,resultlabeld2))